with-expecter: true
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
packages:
  github.com/envoyproxy/envoy/contrib/golang/common/go/api:
    config:
      dir: test/mock/envoy
      outpkg: mock_envoy
    interfaces:
      FilterCallbackHandler:
      ConfigCallbackHandler:
      BufferInstance:
      RequestHeaderMap:
      ResponseHeaderMap:
      CounterMetric:
      GaugeMetric:
  github.com/commoddity/gonvoy:
    config:
      dir: .
      inpackage: true
      filename: "zz_generated.{{ .InterfaceName | lower }}_test.go"
      mockname: "Mock{{.InterfaceName}}"
    interfaces:
      Context:
      Configuration:
      HttpFilterHandler:
      HttpFilterPhaseStrategy:
